package app.familygem

import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import app.familygem.constant.Extra
import app.familygem.constant.Json
import app.familygem.util.TreeUtil
import app.familygem.util.Util
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/** Entry point of the app. */
class LauncherActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.launcher_activity)

        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) { // Tiramisu doesn't need this
            // To update localized strings generated by some static methods
            Global.context = createConfigurationContext(resources.configuration)
        }

        val uri = intent.data
        // By opening the app from the Recents screen, avoids re-importing a newly imported shared tree
        val fromHistory = intent.flags and Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY == Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY
        val startTrees = { startActivity(Intent(this, TreesActivity::class.java)) }
        if (uri != null && !fromHistory) {
            /* The URI could come from a click on various types of links:
                https://www.familygem.app/share.php?tree=20190802224208
                    E.g. in a WhatsApp message
                    Clicked in Chrome in old Androids opens the choice of the app including Family Gem to directly import the tree
                    Normally opens the sharing page on the website
                intent://www.familygem.app/condivisi/20200218134922.zip#Intent;scheme=https;end
                    Official link on the website's sharing page
                    It is the only one that seems guarantee to work, in Chrome, in the browser inside Libero, in the old Android Browser
                https://www.familygem.app/condivisi/20190802224208.zip
                    Direct URL to the ZIP file
                    It works in old Androids, in new ones simply the file is downloaded */
            val dateId = if (uri.path == "/share.php") // Click on the first message received
                uri.getQueryParameter("tree")
            else if (uri.lastPathSegment!!.endsWith(".zip")) // click on the invitation page
                uri.lastPathSegment!!.replace(".zip", "")
            else null
            if (dateId != null) {
                if (BuildConfig.PASS_KEY.isNotEmpty()) {
                    val progressView = findViewById<ProgressView>(R.id.launcher_progress)
                    TreeUtil.launchDownloadSharedTree(lifecycleScope, this, dateId, progressView, startTrees)
                    { progressView.visibility = View.GONE }
                } else {
                    startTrees()
                    Toast.makeText(this, "Missing pass key.", Toast.LENGTH_LONG).show()
                }
            } // The URI comes from a click on a .ged file
            else if (uri.scheme == "file" || uri.scheme == "content") {
                lifecycleScope.launch(Dispatchers.Default) {
                    TreeUtil.importGedcom(this@LauncherActivity, uri, startTrees, startTrees)
                }
            } else {
                startTrees()
                Toast.makeText(this, R.string.cant_understand_uri, Toast.LENGTH_LONG).show()
            }
        } else { // App normal launch
            if (Global.settings.loadTree) { // To load the last opened tree
                startActivity(Intent(this, TreesActivity::class.java).putExtra(Extra.AUTO_LOAD_TREE, true))
            } else startTrees()
        }

        // Retrieves GeoNames username to store it in shared preferences
        if (BuildConfig.PASS_KEY.isNotEmpty()) {
            lifecycleScope.launch(Dispatchers.IO) {
                val credential = U.getCredential(Json.GEO_NAMES)
                if (credential != null) {
                    val editor = Util.getSharedPreferences(this@LauncherActivity)?.edit()
                    editor?.putString(PlaceFinderTextView.GEONAMES_USER, credential.getString(Json.USER))?.apply()
                }
            }
        }

        externalMediaDirs // Just to create the folder /storage/emulated/0/Android/media/app.familygem if it doesn't exist
    }
}
